export CUDA_VISIBLE_DEVICES=4,5,6,7

cd ./prepare

llamafactory-cli train training_scripts/common_sense_reasoning/ARC-c_finetune.yaml
llamafactory-cli train training_scripts/common_sense_reasoning/ARC-e_finetune.yaml
llamafactory-cli train training_scripts/common_sense_reasoning/BoolQ_finetune.yaml
llamafactory-cli train training_scripts/common_sense_reasoning/OBQA_finetune.yaml
llamafactory-cli train training_scripts/common_sense_reasoning/PIQA_finetune.yaml
llamafactory-cli train training_scripts/common_sense_reasoning/HellaSwag_finetune.yaml
llamafactory-cli train training_scripts/common_sense_reasoning/WinoGrande_finetune.yaml
